DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS task;

CREATE TABLE task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  pub_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tstamp INTEGER,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);
